# Generated by Django 4.0.2 on 2022-04-11 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='audio',
            field=models.FileField(upload_to='music/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['mp3', 'wav'])], verbose_name='Аудио'),
        ),
        migrations.AlterField(
            model_name='drumkit',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['zip', 'rar'])], verbose_name='Файл'),
        ),
    ]
