# Generated by Django 4.0.2 on 2022-05-08 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_alter_anketa_audio_alter_drumkit_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.genre', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.price', verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='tonal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.tonal', verbose_name='Тональность'),
        ),
        migrations.AlterField(
            model_name='anketa',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='drumkit',
            name='file',
            field=models.FileField(upload_to='files/%Y/%m/%d/', verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45, verbose_name='Название плейлиста')),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.anketa')),
            ],
        ),
    ]
