# Generated by Django 4.0.2 on 2022-05-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_anketa_genre_alter_anketa_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anketa',
            name='audio',
            field=models.FileField(upload_to='music/%Y/%m/%d/', verbose_name='Аудио'),
        ),
        migrations.RemoveField(
            model_name='catalog',
            name='audio',
        ),
        migrations.AddField(
            model_name='catalog',
            name='audio',
            field=models.ManyToManyField(to='main.Anketa'),
        ),
    ]
