# Generated by Django 4.0.2 on 2022-05-11 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_anketa_audio_remove_catalog_audio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='image',
            field=models.ImageField(null=True, upload_to='playlists/%Y/%m/%d/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='catalog',
            name='audio',
            field=models.ManyToManyField(to='main.Anketa', verbose_name='Треки'),
        ),
    ]
