# Generated by Django 4.0.2 on 2022-05-13 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_catalog_image_alter_catalog_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='image',
            field=models.ImageField(upload_to='playlists/%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
