# Generated by Django 4.0.2 on 2022-05-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_catalog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalog',
            name='slug',
            field=models.SlugField(default=417, max_length=100, unique=True),
        ),
    ]
